version: "3.8"
services:
  git-scraper:
    container_name: containers_scraper_1
    build: "backend/."
    volumes:
      - ./db:/usr/local/bin/db
    environment:
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASSWORD}
      - GIT_URL=${GIT_URL}
      - GIT_PROJECT_NAME=${GIT_PROJECT_NAME}
  superset:
    container_name: containers_superset_1
    build: "superset/."
    ports:
      - 8080:8080
    volumes:
      - ./db:/app/db